---
booktitle: 'Proceedings of the Eleventh International Symposium on Imprecise Probabilities:
  Theories and Applications'
shortname: ISIPTA
sections:
- name: Preface
  title: Preface
- name: Full Papers
  title: Full Papers
- name: Short Papers
  title: Short Papers
year: '2019'
volume: 103
start: 2019-07-03
end: 2019-07-06
published: 2019-06-29
url: http://proceedings.mlr.press
conference_number: '11'
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ISIPTA2019
month: 0
cycles: false
bibtex_editor: De Bock, Jasper and {de Campos}, Cassio P. and {de Cooman}, Gert and
  Quaeghebeur, Erik and Wheeler, Gregory
editor:
- given: Jasper
  family: De Bock
- given: Cassio P.
  family: de Campos
- given: Gert
  family: de Cooman
- given: Erik
  family: Quaeghebeur
- given: Gregory
  family: Wheeler
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eleventh International Symposium on Imprecise Probabilities: Theories and Applications
    Held in Thagaste, Ghent, Belgium on 03-06 July 2019

  Published as Volume 103 by the Proceedings of Machine Learning Research on 29 June 2019.

  Volume Edited by:
    Jasper De Bock
    Cassio P. de Campos
    Gert de Cooman
    Erik Quaeghebeur
    Gregory Wheeler

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 03--06 Jul
baseurl: "/v103"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v103
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: 'International Symposium on Imprecise Probabilities: Theories and Applications'
  url: 
  location: Thagaste, Ghent, Belgium
  dates:
  - 2019-07-03
  - 2019-07-04
  - 2019-07-05
  - 2019-07-06
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
